from flask_app import model
connection = model.connect()
model.create_database(connection)
model.fill_database(connection)
# model.update_ranking(connection)

# model.add_user(connection, 'user(mail)', 'password', 'activité', 'totp') MotDep44ss++
model.add_user(connection, 'admin@ici.net', 'Secret+123456', 'agriculteur')
model.add_user(connection, 'john@ici.net', 'Secret+123456', 'agriculteur')
model.add_user(connection, 'elmout@ici.net', 'Secret+123456', 'consommateur')
model.add_user(connection, 'sébastion@ici.net', 'Secret+123456', 'consommateur')

# model.add_baket(connection, 'title', 'information', 'price', 'creator')
model.add_basket(connection, 'panier01', 'fruits en masse, ici on bouffe si bien que voila.', '65', 'admin@ici.net')
model.add_basket(connection, 'panier03', 'retrouvez ici pléthore de fruits exotiques produits ici en bretagne islandaise', '250', 'admin@ici.net')
model.add_basket(connection, 'panier04', 'légumes +', '665', 'john@ici.net')
model.add_basket(connection, 'panier07', 'légumes si incroyables que vous n en revienddrez pas, ils sont si succulents que mort peut s en suivre', '2657', 'john@ici.net')

# model.add_reservation(connection, 'user', 'basket', 'qtte')
model.add_reservation(connection, 'john@ici.net', 'panier01', '12', '2024-11-02')
model.add_reservation(connection, 'john@ici.net', 'panier03', '8', '2024-11-01')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '3', '2024-11-01')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '7', '2024-11-04')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '15', '2024-11-09')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '1', '2024-11-11')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '9', '2024-11-13')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '3', '2024-11-14')
model.add_reservation(connection, 'elmout@ici.net', 'panier04', '4', '2024-11-20')
model.add_reservation(connection, 'elmout@ici.net', 'panier07', '20', '2024-11-05')
model.add_reservation(connection, 'sébastion@ici.net', 'panier04', '8', '2024-11-11')
model.add_reservation(connection, 'sébastion@ici.net', 'panier04', '4', '2024-11-04')
model.add_reservation(connection, 'sébastion@ici.net', 'panier07', '7', '2024-11-02')
model.add_reservation(connection, 'sébastion@ici.net', 'panier07', '8', '2024-11-09')
model.add_reservation(connection, 'sébastion@ici.net', 'panier07', '3', '2024-11-16')
model.add_reservation(connection, 'sébastion@ici.net', 'panier07', '5', '2024-11-19')
model.add_reservation(connection, 'sébastion@ici.net', 'panier04', '5', '2024-11-03')